### PR TITLE
Adds option to prevent focus of target anchor

### PR DESCRIPTION
**Pull request by janhassel**
In most cases, focusing the target anchor after scrolling to it is desired. However, in a situation where this package is used for a split-screen kinda view, it can be better to keep the focus on the trigger.

This PR adds a new option (`focusAnchor`) to the settings which is `true` by default.

### CODE REVIEW

**Comment by janhassel** [comment]
I agree that this can be problematic for accessibility. Let's look at a sample split-screen use case:

The user is interacting with one side and making changes which affect information shown on the other side of the screen. If the focus switches to the other side everytime a scroll is initiated, a continuous workflow is not possible. This could (and depending on the case probably should) be disabled when accessibility features are detected and the user is relying on a screenreader.

I think it is in the responsibility of the developer to account for this.

**Comment by cferdinandi** [comment]
As far as I know, there's not a good way to detect assistive device use. I feel strongly that it's my responsibility as a project maintainer to prevent developers from breaking things accidentally (or even deliberately because they don't care).

The use case you're describing feels like something you would use the Smooth Scroll API to build up instead of the default behavior.

**Comment by janhassel** [comment]
That's a good point.
Do you think adding a clear warning to the README about the potential consequences would be sufficient?

**Comment by cferdinandi** [comment]
Feels a bit like (warning: super exaggerated example here) building a gun and warning people not to shoot anyone with it because they could die.

**Comment by janhassel** [comment]
I understand your point and think it's honorable that you care a lot about potential consequences for accessibility. My guess is that most people leveraging this package are using it to smoothly scroll within a "regular" page and I see no reason why anyone would want to prevent the target focus in this case. Since this is an optional setting and must be explicitly set by the developer using it, it will only be activated in very specific cases where there is an active need to keep the focus on the trigger. I think giving the developer this option is important when building more complex web applications.

**Comment by janhassel** [comment]
Hey, just checking in again.

Since this package is basically a supercharged, customizable version of the native [Element.scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) API, I took a closer look at that one and noticed that it actually doesn't shift the user's keyboard focus but keeps it where it was before. Though, you can find many stackoverflow threads discussing on how to implement a callback workaround to do so. I think this is a good sign that we're on the right track and focusing the target element is generally wanted, but developers should also have the ability to control it.

**Comment by janhassel** [comment]
Ah, true. For my use case I only used the `animateScroll` method, hence the comparison to `Element.scrollIntoView`.

I thought about implementing a workaround by getting the element's y position and passing that to the `animateScroll` method but would love to use `animateScroll(Element)` instead to make the code clearer and leverage the `getEndLocation` method instead of writing a custom one.

**Comment by cferdinandi** [comment]
I understand. This feels like enough of an edge case, though, that I'd rather not add an option that developers could use (intentionally or not) in bad ways. Sorry!

**Pull request closed without merging**
