### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by cferdinandi**

### CODE REVIEW

**Comment by SoufianeAbid** [comment]
Hello 
Have you been replaced (updateURL) by (scrollOnLoad)
 (scrollOnLoad) not working :!!
index.html#link

**Comment by cferdinandi** [comment]
1. *Have you been replaced (updateURL) by (scrollOnLoad)* Yes
2. *(scrollOnLoad) not working :!!* Demo link please. It's working [on the demo](http://cferdinandi.github.io/smooth-scroll/#bazinga).

**Comment by SoufianeAbid** [comment]
I'm on localhost :+1: 

I want to remove hash links

Experimented

scrollOnLoad  : false   scrollOnLoad : true

Other properties work well

Note : Experimented with version 5 And worked

i am sorry for my english :dancer:

**Comment by cferdinandi** [comment]
Ohh... hash links cannot be removed. They're now fundamental to how smooth scroll works (which allows me to build a less hacky and more better working browser history functionality).

`scrollOnLoad` specifies whether or not Smooth Scroll should animate an anchor link when the page loads.

If you have any other questions, please create a standalone GitHub issue for them. Thanks!

**Comment by SoufianeAbid** [comment]
Thanks you Chris

**Pull request merged**
