### PR TITLE
Support function as offset value

### PR DESCRIPTION
**Pull request by agarzola**
My fixed header changes height depending on viewport size, so I needed to pass in a function to the `offset` parameter that returns an integer based on the viewport size at the moment the animation is invoked. This pull request allows `offset` to be an integer or a function that returns an integer.

---

Note: Only _after_ implementing this did I realize you have a `selectorHeader` option that solves my problem. ¯\_(ツ)_/¯ I’m submitting this pull request anyway in case you see value in it. Something like #259, for instance, might be implemented using a function to calculate this offset on the fly by passing a function that does that.

In any case, thanks for such a useful library!

### CODE REVIEW

**Comment by agarzola** [comment]
I forgot to add: This PR also tracks `jshint@2.x`, which is a peer dep of `gulp-jshint`. It wasn’t tracked before.

**Comment by agarzola** [comment]
Another thing I should point out is that I don’t know JSDoc very well, so I’m not sure how to document the `offset` property’s support for a Number or a Function.

**Comment by cferdinandi** [comment]
Hey, neat idea. I actually think rather than passing in a function, I should add a new setting that tells Smooth Scroll to dynamically grab the header height with each scroll rather than just when it's initialized.

I'm going to close this PR, but open a new issue based on the overall idea behind it. Thanks!

**Comment by agarzola** [comment]
Hey, thanks for taking the time to review this PR! There are other use cases for accepting a function, beyond compensating for a fixed header.

For example, in one of my most recent projects, the design of the page requires me to have a section with an inordinate amount of padding on it. Without getting too much into the weeds, the section above this one has some visual elements that “spill over” to this section, which is why there is extra padding. This _offset as function_ feature helps me set a different offset for just this section to compensate for that extra top padding.

In any case, I (again!) appreciate all your hard work on this library. I’ve used it on several projects now and find it a pleasure to work with!

**Comment by cferdinandi** [comment]
@agarzola Hmm... so in that use case, wouldn't just initing with an offset take care of things for you? Perhaps even setting the offset dynamically on a per-page basis? 

I guess to play devil's advocate here... you can set an offset dynamically without needing to pass a function into the script. Example:

```js
var offset = 0;
if ( // some condition to evaluate against ) {
    offset = 25; // You could do some functional magic here to get the offset
} 

smoothScroll.init({
    offset: offset,
});

**Comment by agarzola** [comment]
@cferdinandi Sorry, I was unclear. I’m talking about consecutive `<section>` elements on the same page. This page has a fixed header, and its content in grouped into `<section>`s. Almost all `<section>` elements on the page have just a bit of top padding, so setting the `offset` value statically on init works well. But there is one `<section>` element whose content spills into the next section, which I achieve through a negative margin and extra top padding on the following `<section>` (let’s call this special section with neg margin and extra padding the Outlier).

It would be helpful to apply a larger offset when smooth scrolling to this one Outlier section. As far as I can tell, there is currently no way to do that. Likewise, I can imagine other design features (beyond a fixed header) that might influence just how much `offset` one might need `smooth-scroll` to apply, and those features might be dynamic, requiring evaluation on the fly.

**Comment by cferdinandi** [comment]
Aha... that actually sounds great! In that case, let me re-review this code and get back to you on next steps. Thanks for clarifying, and for submitting this.

**Comment by cferdinandi** [comment]
Finally got around to revisiting this. Just updated the dependencies, and will be merging this over at https://github.com/cferdinandi/smooth-scroll/pull/318.

Thanks for all of your work here!

**Pull request closed without merging**
