### PR TITLE
definition of root and scoping

### PR DESCRIPTION
**Pull request by alexbeletsky**

### CODE REVIEW

**Comment by cferdinandi** [comment]
@alexbeletsky Thanks so much for this! Quick question: Is the prefixing of all `document` references with `root` necessary or a stylistic choice?

**Comment by alexbeletsky** [comment]
It's not exactly necessary, since it's done implicitly looking in global
space, in case of browser it's 'window'.  But it's a good style and
eliminates lint warnings.

**Comment by alexbeletsky** [comment]
@cferdinandi please ping me once it's merged, I'm currently using modified local version. Would like to fetch it from origin though :)

**Comment by cferdinandi** [comment]
Makes sense, and will do. Just need to update the version number and readme, and run the gulp build so that the `dist` files are updated, too.

**Comment by tscanlin** [comment]
+1 Thank you guys for making this change. I was going nuts trying to figure out why this wasn't working with browserify. :)

**Pull request merged**
