### PR TITLE
Add support for override:scroll containers

### PR DESCRIPTION
**Pull request by yciabaud**
This PR adds support for scrollable divs, I made the scroll relative to the container set to body or by selector.

The container is selected in the ancestors of the clicked link.

What do you think?

### CODE REVIEW

**Comment by cferdinandi** [comment]
This seems to have some overlap with https://github.com/cferdinandi/smooth-scroll/pull/291. I'll need to test both and make sure whatever solution I implement works across a range of use cases. Thanks for this, though.

**Comment by yciabaud** [comment]
Yes it definitely has overlap with the previous PR but it should cover the cases where you can have both smooth scrolling in the body and in scrollable divs by looking for a container using a selector on the click event.

**Comment by cferdinandi** [comment]
This does not behave properly for me. Clicking the `Bazinga!` link that scrolls you to the bottom of the page first jumps you to the top of the page, and then scrolls down.

Similarly, clicking the `Back to the top` link jumps up to the top without an animation.

**Comment by yciabaud** [comment]
You're right, I will have a look at this.

**Comment by cferdinandi** [comment]
Let me ask a different question: why was there a need to change the calculation functions? Couldn't we instead have simply changed the elements the existing functions use (example, the containing `div` instead of `document`)?

**Comment by yciabaud** [comment]
Well correct me if I am wrong but document properties for height and scrollHeight are different in the element API. Scrolling is different too (root.pageYOffset does not work), so I had to replace those functions in all calculation methods.

I have a cleaner (by reusing some of your code) implementation now, can you have a look at it?

I did not found a more straightforward way to do this, let me know if you think about something.

**Comment by cferdinandi** [comment]
I'm still seeing lots of jumpy behavior here, both on the primary `index.html` example and `div.html`.

I suspect this is related to the need to use `scrollTop` instead of `scrollTo` when animating inside a div (though I admittedly have not tested this).

**Comment by yciabaud** [comment]
Yes it is still a bit buggy in firefox, I will have a look tomorrow to see if it is a calculation problem on a `scrollTop` related issue...

**Comment by yciabaud** [comment]
OK figured out something, scrollTop does not work on body in firefox it works on html and chrome does the opposite.

I believe you're right and now I use `window.scrollTo` when scolling the whole page and `element.scrollTop` only for the divs. It looks fine on chrome and firefox, can you check if your issues are gone?

What do you think about the current implementation? Using element API all along the process simplifies the code a little and the overhead for using divs is quite lite IMHO.

**Comment by cferdinandi** [comment]
There's still a jump happening when you click the link. Check out this version, in which I've increased the scroll speed to 2 seconds so everything is slower and easier to see. It's jumping down to the clicked link, then scrolling.

This is happening on the non-div version as well.

https://github.com/cferdinandi/smooth-scroll/tree/yciabaud-master

**Comment by cferdinandi** [comment]
I'm going to close this one out. If you get this working without the jank, please feel free to issue a new PR, though!

**Pull request closed without merging**
