### PR TITLE
Commit changes to allow for offset: center

### PR DESCRIPTION
**Pull request by LostKobrakai**

### CODE REVIEW

**Comment by cferdinandi** [comment]
What does this do?

**Comment by LostKobrakai** [comment]
When using `offset: center` it'll try to vertically center the element in the viewport, as long as it's size is small enough, otherwise it's 0.

**Comment by cferdinandi** [comment]
Is there a use case for this?

**Comment by LostKobrakai** [comment]
I'm currently creating a homepage, where page parts are teased in various sections followed one after another. On the side of the page are numbers, which when clicked jump to the corresponding section. This allows the numbered navigation and the sections to stay nicely aligned as well as those sections nicely replacing each other in the same space.

**Comment by cferdinandi** [comment]
Can I see live demo or something? I don't mean to sound like I'm nitpicking, but I believe strongly in making every feature enhancement fight for it's right to be there.

**Comment by cferdinandi** [comment]
Hey... just wanted to follow-up and see if you had a live demo I could look at.

**Comment by LostKobrakai** [comment]
http://yoga.kobrakai.de/

**Comment by cferdinandi** [comment]
Thanks, makes sense. Let me just run a few tests, but this should be good to include. Thanks!

**Comment by cferdinandi** [comment]
I've decided not to merge this for a few reasons:

1. It feels like a less common edge case that could be handled with the Smooth Scroll API instead of being baked into the core.
2. Your code is well written, but not in keeping with the style of the rest of the script or the contribution guidelines, so I would need to clean it up.
3. You submitted this PR when version 9 was the most recent version. I'm not onto v10 which uses  a very different approach, and would need to true this up with it.

Thanks for your work here, though.

**Pull request closed without merging**
