### PR TITLE
Added new settings 'block' like in Element.scrollIntoView

### PR DESCRIPTION
**Pull request by Cybso**
[Element.scrollIntoView](https://developer.mozilla.org/de/docs/Web/API/Element/scrollIntoView) defines a parameter 'block=start|end' that controls if the target element should be srolled to upper or lower boundary of the viewport.

I've emulated this behaviour in Smooth Scroll and added a third option 'auto' that chooses the placement based on the shortest scrolling distance.

### CODE REVIEW

**Comment by cferdinandi** [comment]
This feels like an edge case better supported via the API. https://cferdinandi.github.io/smooth-scroll/options.html#use-smooth-scroll-events-in-your-own-scripts

**Comment by Cybso** [comment]
I don't think this can be done via the API since it requires to calculate the endPosition  (getEndPosition) based on the bottom position of the anchor element, not on the top one. The "before" callback is execute long after the destinated scroll position and the distance has been calculated. Additionally, the callbacks don't provide any access to the internal data structure, so it isn't even possible to manually recalculate them before the animation starts.

**Comment by cferdinandi** [comment]
I was actually thinking more of a "write your own" type situation using the `animateScroll()` public method. A bit like this: https://cferdinandi.github.io/smooth-scroll/extras.html#scrolling-without-updating-the-url

**Comment by cferdinandi** [comment]
My broader point... this is an edge case that adds additional code to the core for a feature that's not likely to be used by most users and can be supported outside the core using the available public methods.

My goal is to enable as many features as possible while keeping the code base as small as possible.

**Pull request closed without merging**
