### PR TITLE
Fixed Gzip compression issue

### PR DESCRIPTION
**Pull request by SaifurRahmanMohsin**
When used in web framework that use gzip compression it throws "JS Invalid left-hand side expression in postfix operation" issue. See http://stackoverflow.com/questions/11174170/js-invalid-left-hand-side-expression-in-postfix-operation

### CODE REVIEW

**Comment by cferdinandi** [comment]
@SaifurRahmanMohsin

1. I'm unsure what the issue is here. I use this script gzipped via Apache servers without issue, and that StackOverflow thread didn't provide much clarity. That would be fine if I could look at your code, but...
2. You only updated the minified Distribution version of the file, which makes it impossible for me to accurately compare changes. 

I need you to either make the change the source version of the script or instruct me on what the issue is and how to fix it myself. If you make the fix yourself, please adjust the `src` > `js` > `smooth-scroll.js` file, update the version number, update the changelog, and run the Gulp build. This would be a bugfix version, bringing us to 5.3.4.

**Comment by SaifurRahmanMohsin** [comment]
I'm sorry about that. I do acknowledge that it's difficult to see the changes in minified files but I noticed the issue doesn't exist in the original source file that's why I had to change the minified file alone. Anyway here's a screenshot highlighting the change...
screen shot 2015-02-16 at 8 26 44 pm

Anyway, I resolved the issue on my web app immediately and it works great. Thanks for the script

**Comment by cferdinandi** [comment]
@SaifurRahmanMohsin Interesting. So the issue is only in the minified version? Again, I've used that (on gzipped sites) without issue. The minification is handled via [UglifyJS](https://github.com/mishoo/UglifyJS), which is a well recognized/supported tool. This sounds more like an issue with whatever framework you're using than with the script itself, unfortunately.

**Comment by SaifurRahmanMohsin** [comment]
I believe your right. My framework does asset minification when running in production hence the issue. Anyway thanks for your insights.

**Pull request closed without merging**
